let clock = d3.select('.clock')

let face = clock.append('g')
  .classed('face', true)

face.append('circle')
  .classed('circle', true)

let quarterHourScale = d3.scaleLinear()
  .range([0, 360 - 360 / 96])
  .domain([0, 96 - 1])

face.selectAll('.quarter-hour-tick')
  .data(d3.range(0, 96))
  .enter()
  .append('line')
  .classed('quarter-hour-tick', true)
  .attr('x1', '0')
  .attr('x2', '0')
  .attr('y1', '42vmin')
  .attr('y2', '38vmin')
  .attr('transform', d => `rotate(${quarterHourScale(d)})`)

let hourScale = d3.scaleLinear()
  .range([0, 360 - 360 / 24])
  .domain([0, 24 - 1])

face.selectAll('.hour-tick')
  .data(d3.range(0, 24))
  .enter()
  .append('line')
  .classed('hour-tick', true)
  .attr('x1', '0')
  .attr('x2', '0')
  .attr('y1', '42vmin')
  .attr('y2', '38vmin')
  .attr('transform', d => `rotate(${hourScale(d)})`)
